language: php

php:
   - 5.3

env:
   global:
      - secure: "J2fogKRbn9PUduXchvwHAxZDtLWOAqjK6d77Gyr7SRJtygHpoFJSkSvSUam8\nLATUYJ6eE9N3divyQjbq184sajaMAm4BffUbO5rIwbBprACAxW9szJkvFY64\nGZoyBxc3CWRJZqRKgO8quRE8DjKNQ9gE/TWpaN3GKRyehk1cwfs="

before_script:
   - wget http://getcomposer.org/composer.phar
   - sh -c "if $TRAVIS_SECURE_ENV_VARS; then php composer.phar config github-oauth.github.com $GITHUB_OAUTH_TOKEN; else php composer.phar config preferred-install source; fi"
   - php -dmemory_limit=1G composer.phar update --no-interaction

script:
   - ant -Dlib.path.mysql=ant-scripts/jars -Dmysql.root.user=root -Dmysql.root.password="" -Dmoodle.create-database=1 moodle-automation-init
